### ISSUE TITLE
Request bom

### ISSUE THREAD

**Issue by LuckyFishGeek** [ElectronicCats/michi#3]
Is there a detailed BOM, thanks for such a nice piece

**Comment by IvanAmg** [comment]
Hi! @LuckyFishGeek 
You'll be able to see a .csv file under the Release section.
![image](https://user-images.githubusercontent.com/96195073/198092823-f26a2735-4607-4370-9b19-f64587384e91.png)

**Comment by LuckyFishGeek** [comment]
thank you very much! I'm sorry, I'm blind
